# -*- coding: utf-8 -*-
"""Custom_Data_for_Finetuning_LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pD-dK_91qud3ijoCQdnsVhZHoofai3BU

# Imports
"""

import pandas as pd
import csv
import json
from pprint import pprint
import transformers
import accelerate
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding
import transformers
from transformers import logging as hf_logging
from tqdm import tqdm
import datasets
import torch, gc
import logging

df_raw = pd.read_csv('train.csv', delimiter=',')
df_raw.head()

"""Comprehensive Medical Q&A Dataset from Kaggle: https://www.kaggle.com/datasets/thedevastator/comprehensive-medical-q-a-dataset?resource=download"""

df_raw.shape

"""# Config Enviroment"""

logger = logging.getLogger(__name__)
global_config = None

device_count = torch.cuda.device_count()
if device_count > 0:
  logger.debug('Select GPU device')
  device = torch.device('cuda')
else:
  logger.debug('Select CPU device')
  device = torch.device('cpu')

gc.collect()
torch.cuda.empty_cache()

model = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'

"""# Data Process"""

csv_file = 'train.csv'
jsonl_file = 'health.jsonl'

with open(csv_file, mode='r', encoding='utf-8') as f_csv, open(jsonl_file, mode='w', encoding='utf-8') as f_jsonl:
  reader = csv.DictReader(f_csv)
  for row in reader:
    data = {'question': row['Question'], 'answer': row['Answer']}
    f_jsonl.write(json.dumps(data) + '\n')

instruction_health_df = pd.read_json(jsonl_file, lines=True)
examples = instruction_health_df.to_dict()

print(f'Question: {examples["question"][0]} Answer: {examples["answer"][0]}')

prompt_template = """### Question:
{question}

### Answer:"""

num_examples = len(examples['question'])
finetuning_dataset = []

for i in range(num_examples):
  question = examples['question'][i]
  answer = examples['answer'][i]
  text_with_prompt_template = prompt_template.format(question=question)
  finetuning_dataset.append({'question': text_with_prompt_template, 'answer': answer})

tokenizer = AutoTokenizer.from_pretrained(model)

pprint(finetuning_dataset[0])

"""## Tokenization"""

def tokenize_function(examples):
    # Concatena pergunta + resposta, pois o modelo é causal
    if 'question' in examples and 'answer' in examples:
        text = [
            q + a for q, a in zip(examples['question'], examples['answer'])
        ]
    else:
        text = examples['text']

    # Pad_token = eos_token (TinyLlama não tem pad_token por padrão)
    tokenizer.pad_token = tokenizer.eos_token

    # Tokenização padronizada
    tokenized_inputs = tokenizer(
        text,
        return_tensors='pt',
        padding='max_length',
        truncation=True,
        max_length=2048
    )

    # Labels devem ser iguais aos input_ids para causal LM
    tokenized_inputs['labels'] = tokenized_inputs['input_ids'].clone()

    return tokenized_inputs

finetuning_dataset_loaded = datasets.load_dataset('json', data_files=jsonl_file, split='train')

tokenized_dataset = finetuning_dataset_loaded.map(
    tokenize_function,
    batched=True,
    batch_size = 1,
    drop_last_batch = True
)

print(tokenized_dataset)

split_dataset = tokenized_dataset.train_test_split(test_size=0.2, shuffle=True, seed=123)
print(split_dataset)

train_dataset = split_dataset['train']
test_dataset = split_dataset['test']

"""# Training Model"""

base_model = AutoModelForCausalLM.from_pretrained(model)

base_model.config.use_cache = False

dataset_path = f'/content/{jsonl_file}'
use_hf = False

training_config = {
    'model': {
        'pretrainend_name': model,
        'max_length': 2048
    },
    'datasets': {
        'use_hf': use_hf,
        'path': dataset_path
    },
    'verbose': True
}

def inference(text, model, tokenizer, max_input_tokens = 1000, max_output_tokens=100):
  input_ids = tokenizer.encode(
     text,
     return_tensors = 'pt',
     truncation=True,
     max_length = max_input_tokens
  )
  device = model.device
  generated_tokens_with_prompt = model.generate(
      input_ids = input_ids.to(device),
      max_length = max_output_tokens
  )
  generated_text_with_prompt = tokenizer.batch_decode(generated_tokens_with_prompt, skip_special_tokens=True)
  generated_text_answer = generated_text_with_prompt[0][len(text):]

  return generated_text_answer

test_text = test_dataset[1]['question']
print("Question input (test):", test_text)
print(f"Correct answer docs: {test_dataset[1]['answer']}")
print("Model's answer: ")
print(inference(test_text, base_model, tokenizer))

"""## Setup Training"""

max_steps = 3

trained_model_name = f'{model}_{max_steps}_steps'
output_dir = trained_model_name

training_args = TrainingArguments(
    learning_rate = 1.0e-5,
    num_train_epochs = 3,
    max_steps = max_steps,
    per_device_train_batch_size = 4,
    output_dir = output_dir,
    overwrite_output_dir = False,
    disable_tqdm = False,
    eval_steps = 120,
    save_steps = 120,
    warmup_steps = 1,
    per_device_eval_batch_size = 1,
    eval_strategy = 'steps',
    logging_strategy = 'steps',
    logging_steps = 1,
    optim = 'adafactor',
    gradient_accumulation_steps = 4,
    gradient_checkpointing = True,
    load_best_model_at_end = True,
    save_total_limit= 1,
    metric_for_best_model = 'eval_loss',
    greater_is_better = False,
    report_to='none'
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model = base_model,
    args = training_args,
    train_dataset= train_dataset,
    eval_dataset= test_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator
)

training_output = trainer.train()

save_dir = f'{output_dir} / final'
trainer.save_model(save_dir)
print(f'Saved model: {save_dir}')

"""# Assessment"""

finetuned_model = AutoModelForCausalLM.from_pretrained(save_dir, local_files_only=True)
finetuned_model.to(device)

test_text = test_dataset[1]['question']
print("Question input (test):", test_text)
original_answer = test_dataset[1]['answer']
print(f"Correct answer docs: {original_answer}")

test_text = f"### Question:\n{test_dataset[1]['question']}\n\n### Answer:"
print("Model's answer:")
generated_answer = inference(text=test_text, model=finetuned_model, tokenizer=tokenizer)
print(generated_answer)

def is_exact_match(a, b):
  return a.strip() == b.strip

finetuned_model.eval()

exact_match = is_exact_match(original_answer, generated_answer)
print(f"Exact Match: {exact_match}")

n = 10
metrics = {'exact_matches': []}
predictions = []
example_test_dataset = test_dataset.select(range(10))

example_test_dataset

for i, item in tqdm(enumerate(example_test_dataset)):
  question = f"### Question:\n{item['question']}\n\n### Answer:"
  answer = item['answer']

  try:
    predicted_answer = inference(question, finetuned_model, tokenizer)
  except:
    continue
  predictions.append([predicted_answer, answer])

  exact_match = is_exact_match(predicted_answer, answer)
  metrics['exact_matches'].append(exact_match)

print(f'Number of exact matches: {sum(metrics['exact_matches'])}')

df_predictions = pd.DataFrame(predictions, columns=['predicted_answer', 'target_answer'])
df_predictions.head()